export const Projects = [
    {
        projectName: "Recycling is Fun!",
        date: "01-06-2022",
        image: "/project_pictures/recycling-is-fun.jpg",
        role: "Game Developer",
        description: "A fun and educational game that teaches players about the recycling process and its importance.",
        link: "/projects/recycling-is-fun",
        skills: ["Python", "Pygame"],
    },
        {
        projectName: "bingeworthy",
        date: "01-08-2023",
        image: "/project_pictures/bingeworthy.JPG",
        role: "Web Developer",
        description: "A web application that allows users to track their favorite TV shows and receive recommendations based on their viewing history.",
        link: "/projects/bingeworthy",
        skills: ["HTML", "CSS", "Flask", "SQL", "Python"],
    },
        {
        projectName: "BrainHack 2024",
        date: "01-06-2024",
        image: "/project_pictures/brainhack.png",
        role: "AI/ML Engineer",
        description: "An AI/ML hackathon that focuses on Object Detection, Question Answering and Automatic Speech Recognition.",
        link: "/projects/brainhack-2024",
        skills: ["HuggingFace", "PyTorch", "Python", "Docker"],
    },
        {
        projectName: "Captcha Recognition",
        date: "01-10-2024",
        image: "/project_pictures/captcha-recognition.png",
        role: "AI/ML Engineer",
        description: "A project focused on recognizing and solving CAPTCHAs using advanced machine learning techniques.",
        link: "/projects/captcha-recognition",
        skills: ["PyTorch", "Python", "Computer Vision"],
    },
        {
        projectName: "Sarcasm Detection in Singaporean News",
        date: "01-04-2025",
        image: "/project_pictures/sarcasm_detection.jpg",
        role: "AI/ML Engineer",
        description: "A project focused on detecting sarcasm in news articles from Singapore.",
        link: "/projects/sarcasm-detection",
        skills: ["PyTorch", "Python", "NLP", "HuggingFace"],
    },
        {
        projectName: "Discord Clone",
        date: "01-09-2024",
        image: "/project_pictures/discord.png",
        role: "App Developer",
        description: "A clone of the popular Discord application, focusing on voice chat functionality.",
        link: "/projects/discord-clone",
        skills: ["Python", "Web Sockets", "Locks"],
    }
]